@startuml jeep

class Jeep{
 +ChangedPosition: EventHandler?
 -visitors: int
 -jeepID: int
 -worldLocation: Vector3
  /' for a* representation for the pathfinding '/
 -currentGridPosition: GridPosition
 -nextJoint: GridPosition
 -destination: Destination

 +OnRemove() : void
}

enum Destination{
    ENTRANCE
    EXIT
}

@enduml