@startuml

class Jeep{
 -visitors: int
 -jeepID: int
 -worldLocation: Vector3
  /' for a* representation for the pathfinding '/
 -currentGridPosition: GridPosition
 -nextJoint: GridPosition
 -destination: Destination

 +RevealEntity()
 +OnRemove()
}

enum Destination{
    ENTRANCE
    EXIT
}

@enduml