@startuml mapUml
class Map{
    +EntranceCoords: GridPosition
    +ExitCoords: GridPosition
    +ChangeTerrainAt(factory: TerrainFactory, position: GridPosition)
    +TerrainAt(position: GridPosition): Terrain
}

class GridPosition{
    +x:int
    +y:int
}

interface Terrain{
    +CanPlaceRoad():boolean
}

class Ground{}

abstract class Plant{

}

class Road{

}

class Water{

}

Map "1" *-- "*\n-grid" Terrain
Terrain <|.. Ground
Terrain <|.. Plant
Terrain <|.. Road
Terrain <|.. Water


interface TerrainFactory{
    +CreateTerrain():Terrain
}

@enduml