@startuml

class MoneyManager{
  -visitMotivation: float 
  -ticketPrice: int 
  -listOfAnimals:Animal
  -divesrsityFactor:int
  -money:int
  
  
/' visitMotivation is derived from 
ticketprice and divesrsity and overall number of animals '/
 +CalculateDiversityFactor(): void
 +CalculateVisitMotivation(): void
 

}
@enduml