@startuml

class Safari{
    +Victory: EventHandler?
    +Defeat: EventHandler?
    +JeepCollectionChanged: EventHandler?
    +AnimalCollectionChanged: EventHandler?
    -instance: Safari
    +GetInstance():Safari

}

Safari "1" *-- "1" Map
Safari  *-- "*\n-animals" Animal
Safari  *-- "*\n-jeeps" Jeep
Safari "1" *-- "1" MoneyManager
@enduml