@startuml
namespace View{
class JeepShopUIController{
    +OnSellClick():void
    +OnBuyClick():void
    +OnClose():void
    +Open():void
}

class GhostJeepDisplay{
    +jeepPrefabs: GameObject[]
}
}
Class Unity.MonoBehaviour{}
JeepShopUIController --|> MonoBehaviour
GhostJeepDisplay --|> MonoBehaviour
GhostJeepDisplay -left- "-jeep" Model.Jeep: displays >
JeepShopUIController *-- GhostJeepDisplay : displays >
@enduml 
