@startuml
namespace View{
class MinimapUIController{
    +OnClick(): void

}

class CameraController{
    +OnGoUp(): void
    +OnGoDown(): void
    +OnGoLeft(): void
    +OnGoRight(): void
    
}
}
MinimapUIController -up-|> Unity.MonoBehaviour
MinimapUIController -up- "-map" Model.Map: displays >
@enduml