@startuml
namespace View{
class AnimalDisplay{
    +animalPrefabs: GameObject[]
}



class AnimalCollectionController{

}
}

class Model.Safari{}
Class Model.Animal{}
Class Unity.MonoBehaviour{}
AnimalDisplay --|> MonoBehaviour
AnimalDisplay --- "-animal" Animal: displays >

AnimalCollectionController *-- "-displayers" AnimalDisplay: manages lifecycle >

AnimalCollectionController -- Safari: watches the animal collection > 
@enduml