@startuml
namespace View{
class AnimalShopUIController{
    +OnSellClick():void
    +OnClose():void
    +Open():void
}

class AnimalShopListingController{
    -notEnoughMoney: boolean
    +Selected: UnityEvent
    +OnClick(): void
    +SetNotEnoughMoneyState(s: boolean): void
}

class GhostAnimalDisplay{
    +animalPrefabs: GameObject[]
}

abstract class AnimalShopItem{
    +icon: GameObject
}

class AnimalMetadata{
    +cost: int
    +sellsFor: int
}
}

class Unity.ScriptableObject{}
class Unity.MonoBehaviour{}
class Model.Animal{}


AnimalShopItem --|> ScriptableObject
AnimalShopUIController --|> MonoBehaviour
AnimalShopListingController --|> MonoBehaviour
GhostAnimalDisplay  --|> MonoBehaviour
AnimalShopUIController  o-- "1\n+shopItems" AnimalShopItem

AnimalShopUIController *-- "*" AnimalShopListingController : creates >

AnimalShopListingController -- "shopItem" AnimalShopItem : displays >

GhostAnimalDisplay -right- "-animal" Animal: displays >

AnimalShopItem o-- AnimalMetadata

AnimalShopUIController *-- GhostAnimalDisplay : displays >
@enduml