@startuml
class BuildingUIController{
    +OnDemolishClick():void
    +OnClose():void
    +Open():void
}

class BuilderGridController{
    +IsOpened:bool
    +Open()
    +Close()
}

class BuilderCell{
    -isHovered: bool
    -isForbidden: bool
    +OnClick()
    +OnHover()
    +SetForbiddenState(forbidden:bool)
}

BuilderGridController "1\n-controller" *-- "*\n-cells" BuilderCell

BuildingUIController  o-- "1\n-grid" BuilderGridController

BuildingUIController  o-- "1\n+fields" FieldShopItem

abstract class FieldShopItem{
    +icon: GameObject
    
}

class FieldMetadata{
    +cost:int
    +refundAmount: int
}

FieldShopItem --|> ScriptableObject
BuildingUIController --|> MonoBehaviour
BuilderGridController --|> MonoBehaviour
BuilderCell --|> MonoBehaviour
FieldShopItem ..|> FieldFactory
FieldShopItem o-- FieldMetadata

@enduml