@startuml
class View.MainMenuUIController{
    +OnStartGameClick()
    +OnDifficulyEasyClick()
    +OnDifficultyMediumClick()
    +OnDifficultyHardClick()
}

    Unity.MonoBehaviour <|-- MainMenuUIController 

@enduml