@startuml
class MainMenuUIController{
    +OnStartGameClick()
    +OnDifficulyEasyClick()
    +OnDifficultyMediumClick()
    +OnDifficultyHardClick()
}

    MonoBehaviour <|-- MainMenuUIController 

@enduml